version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:  yarn ng build
      # - run:  yarn ng test
      - run:
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD kkhenissi.azurecr.io
      - run:
          command: |
            docker build -t kkhenissi.azurecr.io/quartesure:1.0 .

      - run:
          command: |
            docker  push kkhenissi.azurecr.io/quarteSure:1.0


